// This file is used by Code Analysis to maintain SuppressMessage attributes that are applied to this
// project. Project-level suppressions either have no target or are given a specific target and
// scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2237:Mark ISerializable types with serializable", Justification = "Serializable not available with NET Standard framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.AmlException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2237:Mark ISerializable types with serializable", Justification = "Serializable not available with NET Standard framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.YotiProfileException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2237:Mark ISerializable types with serializable", Justification = "Serializable not available with NET Standard framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.DynamicShareException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1032:Implement standard exception constructors", Justification = "Parameterless exception constructor is useless in this instance, we should remove this option", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.AmlException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1032:Implement standard exception constructors", Justification = "Parameterless exception constructor is useless in this instance, we should remove this option", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.YotiProfileException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1032:Implement standard exception constructors", Justification = "Parameterless exception constructor is useless in this instance, we should remove this option", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.DynamicShareException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Justification = "String is preferable", Scope = "member", Target = "~M:Yoti.Auth.Images.Image.GetBase64URI~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "FXCop incorrectly identifying Guid.ToString() as having a locale option", Scope = "member", Target = "~M:Yoti.Auth.CryptoEngine.GenerateNonce~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2237:Mark ISerializable types with serializable", Justification = "[Serializable] not available in 'netstandard' target framework", Scope = "type", Target = "~T:Yoti.Auth.YotiProfileException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "[ISerializable] not available in 'netstandard' target framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.AmlException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "[ISerializable] not available in 'netstandard' target framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.YotiProfileException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "[ISerializable] not available in 'netstandard' target framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.DynamicShareException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "[ISerializable] not available in 'netstandard' target framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.ExtraDataException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "We don't want any exception to stop the remaining attributes from being parsed, so we need to catch the general exception", Scope = "member", Target = "~M:Yoti.Auth.Attribute.AttributeConverter.ConvertToBaseAttributes(Yoti.Auth.ProtoBuf.Attribute.AttributeList)~System.Collections.Generic.Dictionary{System.String,Yoti.Auth.Attribute.BaseAttribute}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1724:The type name Extension conflicts in whole or in part with the namespace name 'Org.BouncyCastle.X509.Extension'. Change either name to eliminate the conflict.", Justification = "Since this is a class library, clients can fully qualify the name to avoid this ambiguity", Scope = "type", Target = "~T:Yoti.Auth.ShareUrl.Extensions.Extension`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "used when creating the DynamicPolicy JSON", Scope = "member", Target = "~F:Yoti.Auth.ShareUrl.Policy.DynamicPolicy._isWantedRememberMeIdOptional")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2237:Mark ISerializable types with serializable", Justification = "[Serializable] not available in 'netstandard' target framework", Scope = "type", Target = "~T:Yoti.Auth.Exceptions.ExtraDataException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1128:Unused \"using\" should be removed", Justification = "This using is required for the .NET classic frameworks: .NET 4.5, 4.6, 4.7 & 4.8")]