// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0041:Use 'is null' check", Justification = "Code generated by protobuf compiler", Scope = "member", Target = "~M:AttrpubapiV1.AttributeAndIdList.Equals(AttrpubapiV1.AttributeAndIdList)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0041:Use 'is null' check", Justification = "Code generated by protobuf compiler", Scope = "member", Target = "~M:AttrpubapiV1.AttributeSigning.Equals(AttrpubapiV1.AttributeSigning)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0041:Use 'is null' check", Justification = "Code generated by protobuf compiler", Scope = "member", Target = "~M:AttrpubapiV1.AttributeList.Equals(AttrpubapiV1.AttributeList)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0041:Use 'is null' check", Justification = "Code generated by protobuf compiler", Scope = "member", Target = "~M:AttrpubapiV1.AttributeAndId.Equals(AttrpubapiV1.AttributeAndId)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0041:Use 'is null' check", Justification = "Code generated by protobuf compiler", Scope = "member", Target = "~M:CompubapiV1.EncryptedData.Equals(CompubapiV1.EncryptedData)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0041:Use 'is null' check", Justification = "Code generated by protobuf compiler", Scope = "member", Target = "~M:CompubapiV1.SignedTimestamp.Equals(CompubapiV1.SignedTimestamp)~System.Boolean")]