# Minimal SonarCloud-only pipeline for testing
# This is a temporary pipeline to test SonarCloud configuration

trigger:
  branches:
    include:
    - release/3.18.0

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Yoti SonarCloud'
    organization: 'getyoti'
    scannerMode: 'MSBuild'
    projectKey: 'getyoti:dotnet'
    projectName: '.NET SDK'
    projectVersion: '3.18.0'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
      sonar.links.scm = https://github.com/getyoti/yoti-dotnet-sdk
      sonar.exclusions = src/Yoti.Auth/ProtoBuf/**,src/Examples/**,**/obj/**,**/*.dll,src/Yoti.Auth/DigitalIdentity/**
  displayName: SonarCloud Prepare Analysis

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET 8.0 SDK'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: Restore Solution

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:SkipInvalidConfigurations=false'
  displayName: Build Solution (Minimal)

- task: SonarCloudAnalyze@1
  displayName: Sonar Cloud Analyze

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: Sonar Cloud Publish