// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Attribute.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yoti.Auth.ProtoBuf.Attribute {

  /// <summary>Holder for reflection information generated from Attribute.proto</summary>
  public static partial class AttributeReflection {

    #region Descriptor
    /// <summary>File descriptor for Attribute.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AttributeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9BdHRyaWJ1dGUucHJvdG8SDWF0dHJwdWJhcGlfdjEaEUNvbnRlbnRUeXBl",
            "LnByb3RvIoIBCglBdHRyaWJ1dGUSDAoEbmFtZRgBIAEoCRINCgV2YWx1ZRgC",
            "IAEoDBIwCgxjb250ZW50X3R5cGUYAyABKA4yGi5hdHRycHViYXBpX3YxLkNv",
            "bnRlbnRUeXBlEiYKB2FuY2hvcnMYBCADKAsyFS5hdHRycHViYXBpX3YxLkFu",
            "Y2hvciKYAQoGQW5jaG9yEhUKDWFydGlmYWN0X2xpbmsYASABKAwSGwoTb3Jp",
            "Z2luX3NlcnZlcl9jZXJ0cxgCIAMoDBIaChJhcnRpZmFjdF9zaWduYXR1cmUY",
            "AyABKAwSEAoIc3ViX3R5cGUYBCABKAkSEQoJc2lnbmF0dXJlGAUgASgMEhkK",
            "EXNpZ25lZF90aW1lX3N0YW1wGAYgASgMQmwKJGNvbS55b3RpLmFwaS5jbGll",
            "bnQuc3BpLnJlbW90ZS5wcm90b0IJQXR0clByb3RvWg15b3RpcHJvdG9hdHRy",
            "qgIcWW90aS5BdXRoLlByb3RvQnVmLkF0dHJpYnV0ZcoCCkF0dHJwdWJhcGli",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Yoti.Auth.ProtoBuf.Attribute.ContentTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Yoti.Auth.ProtoBuf.Attribute.Attribute), global::Yoti.Auth.ProtoBuf.Attribute.Attribute.Parser, new[]{ "Name", "Value", "ContentType", "Anchors" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Yoti.Auth.ProtoBuf.Attribute.Anchor), global::Yoti.Auth.ProtoBuf.Attribute.Anchor.Parser, new[]{ "ArtifactLink", "OriginServerCerts", "ArtifactSignature", "SubType", "Signature", "SignedTimeStamp" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Attribute : pb::IMessage<Attribute> {
    private static readonly pb::MessageParser<Attribute> _parser = new pb::MessageParser<Attribute>(() => new Attribute());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Attribute> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yoti.Auth.ProtoBuf.Attribute.AttributeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attribute() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attribute(Attribute other) : this() {
      name_ = other.name_;
      value_ = other.value_;
      contentType_ = other.contentType_;
      anchors_ = other.anchors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attribute Clone() {
      return new Attribute(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private pb::ByteString value_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content_type" field.</summary>
    public const int ContentTypeFieldNumber = 3;
    private global::Yoti.Auth.ProtoBuf.Attribute.ContentType contentType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yoti.Auth.ProtoBuf.Attribute.ContentType ContentType {
      get { return contentType_; }
      set {
        contentType_ = value;
      }
    }

    /// <summary>Field number for the "anchors" field.</summary>
    public const int AnchorsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Yoti.Auth.ProtoBuf.Attribute.Anchor> _repeated_anchors_codec
        = pb::FieldCodec.ForMessage(34, global::Yoti.Auth.ProtoBuf.Attribute.Anchor.Parser);
    private readonly pbc::RepeatedField<global::Yoti.Auth.ProtoBuf.Attribute.Anchor> anchors_ = new pbc::RepeatedField<global::Yoti.Auth.ProtoBuf.Attribute.Anchor>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Yoti.Auth.ProtoBuf.Attribute.Anchor> Anchors {
      get { return anchors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Attribute);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Attribute other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Value != other.Value) return false;
      if (ContentType != other.ContentType) return false;
      if(!anchors_.Equals(other.anchors_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (ContentType != 0) hash ^= ContentType.GetHashCode();
      hash ^= anchors_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (ContentType != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ContentType);
      }
      anchors_.WriteTo(output, _repeated_anchors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (ContentType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ContentType);
      }
      size += anchors_.CalculateSize(_repeated_anchors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Attribute other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      if (other.ContentType != 0) {
        ContentType = other.ContentType;
      }
      anchors_.Add(other.anchors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
          case 24: {
            contentType_ = (global::Yoti.Auth.ProtoBuf.Attribute.ContentType) input.ReadEnum();
            break;
          }
          case 34: {
            anchors_.AddEntriesFrom(input, _repeated_anchors_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Anchor : pb::IMessage<Anchor> {
    private static readonly pb::MessageParser<Anchor> _parser = new pb::MessageParser<Anchor>(() => new Anchor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Anchor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yoti.Auth.ProtoBuf.Attribute.AttributeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Anchor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Anchor(Anchor other) : this() {
      artifactLink_ = other.artifactLink_;
      originServerCerts_ = other.originServerCerts_.Clone();
      artifactSignature_ = other.artifactSignature_;
      subType_ = other.subType_;
      signature_ = other.signature_;
      signedTimeStamp_ = other.signedTimeStamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Anchor Clone() {
      return new Anchor(this);
    }

    /// <summary>Field number for the "artifact_link" field.</summary>
    public const int ArtifactLinkFieldNumber = 1;
    private pb::ByteString artifactLink_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ArtifactLink {
      get { return artifactLink_; }
      set {
        artifactLink_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "origin_server_certs" field.</summary>
    public const int OriginServerCertsFieldNumber = 2;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_originServerCerts_codec
        = pb::FieldCodec.ForBytes(18);
    private readonly pbc::RepeatedField<pb::ByteString> originServerCerts_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> OriginServerCerts {
      get { return originServerCerts_; }
    }

    /// <summary>Field number for the "artifact_signature" field.</summary>
    public const int ArtifactSignatureFieldNumber = 3;
    private pb::ByteString artifactSignature_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ArtifactSignature {
      get { return artifactSignature_; }
      set {
        artifactSignature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sub_type" field.</summary>
    public const int SubTypeFieldNumber = 4;
    private string subType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SubType {
      get { return subType_; }
      set {
        subType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 5;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signed_time_stamp" field.</summary>
    public const int SignedTimeStampFieldNumber = 6;
    private pb::ByteString signedTimeStamp_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SignedTimeStamp {
      get { return signedTimeStamp_; }
      set {
        signedTimeStamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Anchor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Anchor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ArtifactLink != other.ArtifactLink) return false;
      if(!originServerCerts_.Equals(other.originServerCerts_)) return false;
      if (ArtifactSignature != other.ArtifactSignature) return false;
      if (SubType != other.SubType) return false;
      if (Signature != other.Signature) return false;
      if (SignedTimeStamp != other.SignedTimeStamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ArtifactLink.Length != 0) hash ^= ArtifactLink.GetHashCode();
      hash ^= originServerCerts_.GetHashCode();
      if (ArtifactSignature.Length != 0) hash ^= ArtifactSignature.GetHashCode();
      if (SubType.Length != 0) hash ^= SubType.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (SignedTimeStamp.Length != 0) hash ^= SignedTimeStamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ArtifactLink.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ArtifactLink);
      }
      originServerCerts_.WriteTo(output, _repeated_originServerCerts_codec);
      if (ArtifactSignature.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(ArtifactSignature);
      }
      if (SubType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SubType);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Signature);
      }
      if (SignedTimeStamp.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SignedTimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ArtifactLink.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ArtifactLink);
      }
      size += originServerCerts_.CalculateSize(_repeated_originServerCerts_codec);
      if (ArtifactSignature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ArtifactSignature);
      }
      if (SubType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubType);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (SignedTimeStamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SignedTimeStamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Anchor other) {
      if (other == null) {
        return;
      }
      if (other.ArtifactLink.Length != 0) {
        ArtifactLink = other.ArtifactLink;
      }
      originServerCerts_.Add(other.originServerCerts_);
      if (other.ArtifactSignature.Length != 0) {
        ArtifactSignature = other.ArtifactSignature;
      }
      if (other.SubType.Length != 0) {
        SubType = other.SubType;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      if (other.SignedTimeStamp.Length != 0) {
        SignedTimeStamp = other.SignedTimeStamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ArtifactLink = input.ReadBytes();
            break;
          }
          case 18: {
            originServerCerts_.AddEntriesFrom(input, _repeated_originServerCerts_codec);
            break;
          }
          case 26: {
            ArtifactSignature = input.ReadBytes();
            break;
          }
          case 34: {
            SubType = input.ReadString();
            break;
          }
          case 42: {
            Signature = input.ReadBytes();
            break;
          }
          case 50: {
            SignedTimeStamp = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
