// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ContentType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yoti.Auth.ProtoBuf.Attribute {

  /// <summary>Holder for reflection information generated from ContentType.proto</summary>
  public static partial class ContentTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ContentType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContentTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDb250ZW50VHlwZS5wcm90bxINYXR0cnB1YmFwaV92MSppCgtDb250ZW50",
            "VHlwZRINCglVTkRFRklORUQQABIKCgZTVFJJTkcQARIICgRKUEVHEAISCAoE",
            "REFURRADEgcKA1BORxAEEggKBEpTT04QBRIPCgtNVUxUSV9WQUxVRRAGEgcK",
            "A0lOVBAHQucBCiRjb20ueW90aS5hcGkuY2xpZW50LnNwaS5yZW1vdGUucHJv",
            "dG9CEENvbnRlbnRUeXBlUHJvdG9aL2dpdGh1Yi5jb20vZ2V0eW90aS95b3Rp",
            "LWdvLXNkay92My95b3RpcHJvdG9hdHRyqgIcWW90aS5BdXRoLlByb3RvQnVm",
            "LkF0dHJpYnV0ZcoCGFlvdGlcUHJvdG9idWZcQXR0cnB1YmFwaeICJFlvdGlc",
            "UHJvdG9idWZcQXR0cnB1YmFwaVxHUEJNZXRhZGF0YeoCGllvdGk6OlByb3Rv",
            "YnVmOjpBdHRycHViYXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Yoti.Auth.ProtoBuf.Attribute.ContentType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ContentType {
    [pbr::OriginalName("UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("STRING")] String = 1,
    [pbr::OriginalName("JPEG")] Jpeg = 2,
    [pbr::OriginalName("DATE")] Date = 3,
    [pbr::OriginalName("PNG")] Png = 4,
    [pbr::OriginalName("JSON")] Json = 5,
    [pbr::OriginalName("MULTI_VALUE")] MultiValue = 6,
    [pbr::OriginalName("INT")] Int = 7,
  }

  #endregion

}

#endregion Designer generated code
