// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QrCodeMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yoti.Auth.ProtoBuf.Qr {

  /// <summary>Holder for reflection information generated from QrCodeMsg.proto</summary>
  public static partial class QrCodeMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for QrCodeMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QrCodeMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9RckNvZGVNc2cucHJvdG8SC3FycHViYXBpX3YxIpIBCglRckNvZGVNc2cS",
            "IwoGaXNzdWVyGAEgASgOMhMucXJwdWJhcGlfdjEuSXNzdWVyEhUKDXNoYXJp",
            "bmdfdG9rZW4YAiABKAwSDgoGcmVmX2lkGAMgASgMEg4KBnBvbGljeRgEIAEo",
            "DBIpCgl0cmFuc3BvcnQYBiABKA4yFi5xcnB1YmFwaV92MS5UcmFuc3BvcnQq",
            "KwoGSXNzdWVyEhQKEFVOREVGSU5FRF9JU1NVRVIQABILCgdDT05ORUNUEAEq",
            "MAoJVHJhbnNwb3J0Eg0KCVVOREVGSU5FRBAAEgcKA1VSSRABEgsKB1FSX0NP",
            "REUQAkLUAQokY29tLnlvdGkuYXBpLmNsaWVudC5zcGkucmVtb3RlLnByb3Rv",
            "Qg5RckNvZGVNc2dQcm90b1otZ2l0aHViLmNvbS9nZXR5b3RpL3lvdGktZ28t",
            "c2RrL3YzL3lvdGlwcm90b3FyqgIVWW90aS5BdXRoLlByb3RvQnVmLlFyygIW",
            "WW90aVxQcm90b2J1ZlxRcnB1YmFwaeICIllvdGlcUHJvdG9idWZcUXJwdWJh",
            "cGlcR1BCTWV0YWRhdGHqAhZZb3RpLlByb3RvYnVmLlFycHViYXBpYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Yoti.Auth.ProtoBuf.Qr.Issuer), typeof(global::Yoti.Auth.ProtoBuf.Qr.Transport), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Yoti.Auth.ProtoBuf.Qr.QrCodeMsg), global::Yoti.Auth.ProtoBuf.Qr.QrCodeMsg.Parser, new[]{ "Issuer", "SharingToken", "RefId", "Policy", "Transport" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Issuer {
    [pbr::OriginalName("UNDEFINED_ISSUER")] UndefinedIssuer = 0,
    [pbr::OriginalName("CONNECT")] Connect = 1,
  }

  public enum Transport {
    [pbr::OriginalName("UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("URI")] Uri = 1,
    [pbr::OriginalName("QR_CODE")] QrCode = 2,
  }

  #endregion

  #region Messages
  public sealed partial class QrCodeMsg : pb::IMessage<QrCodeMsg> {
    private static readonly pb::MessageParser<QrCodeMsg> _parser = new pb::MessageParser<QrCodeMsg>(() => new QrCodeMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QrCodeMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yoti.Auth.ProtoBuf.Qr.QrCodeMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QrCodeMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QrCodeMsg(QrCodeMsg other) : this() {
      issuer_ = other.issuer_;
      sharingToken_ = other.sharingToken_;
      refId_ = other.refId_;
      policy_ = other.policy_;
      transport_ = other.transport_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QrCodeMsg Clone() {
      return new QrCodeMsg(this);
    }

    /// <summary>Field number for the "issuer" field.</summary>
    public const int IssuerFieldNumber = 1;
    private global::Yoti.Auth.ProtoBuf.Qr.Issuer issuer_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yoti.Auth.ProtoBuf.Qr.Issuer Issuer {
      get { return issuer_; }
      set {
        issuer_ = value;
      }
    }

    /// <summary>Field number for the "sharing_token" field.</summary>
    public const int SharingTokenFieldNumber = 2;
    private pb::ByteString sharingToken_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SharingToken {
      get { return sharingToken_; }
      set {
        sharingToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ref_id" field.</summary>
    public const int RefIdFieldNumber = 3;
    private pb::ByteString refId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString RefId {
      get { return refId_; }
      set {
        refId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "policy" field.</summary>
    public const int PolicyFieldNumber = 4;
    private pb::ByteString policy_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Policy {
      get { return policy_; }
      set {
        policy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transport" field.</summary>
    public const int TransportFieldNumber = 6;
    private global::Yoti.Auth.ProtoBuf.Qr.Transport transport_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yoti.Auth.ProtoBuf.Qr.Transport Transport {
      get { return transport_; }
      set {
        transport_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QrCodeMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QrCodeMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Issuer != other.Issuer) return false;
      if (SharingToken != other.SharingToken) return false;
      if (RefId != other.RefId) return false;
      if (Policy != other.Policy) return false;
      if (Transport != other.Transport) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Issuer != 0) hash ^= Issuer.GetHashCode();
      if (SharingToken.Length != 0) hash ^= SharingToken.GetHashCode();
      if (RefId.Length != 0) hash ^= RefId.GetHashCode();
      if (Policy.Length != 0) hash ^= Policy.GetHashCode();
      if (Transport != 0) hash ^= Transport.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Issuer != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Issuer);
      }
      if (SharingToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(SharingToken);
      }
      if (RefId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(RefId);
      }
      if (Policy.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Policy);
      }
      if (Transport != 0) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Transport);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Issuer != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Issuer);
      }
      if (SharingToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SharingToken);
      }
      if (RefId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RefId);
      }
      if (Policy.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Policy);
      }
      if (Transport != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Transport);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QrCodeMsg other) {
      if (other == null) {
        return;
      }
      if (other.Issuer != 0) {
        Issuer = other.Issuer;
      }
      if (other.SharingToken.Length != 0) {
        SharingToken = other.SharingToken;
      }
      if (other.RefId.Length != 0) {
        RefId = other.RefId;
      }
      if (other.Policy.Length != 0) {
        Policy = other.Policy;
      }
      if (other.Transport != 0) {
        Transport = other.Transport;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            issuer_ = (global::Yoti.Auth.ProtoBuf.Qr.Issuer) input.ReadEnum();
            break;
          }
          case 18: {
            SharingToken = input.ReadBytes();
            break;
          }
          case 26: {
            RefId = input.ReadBytes();
            break;
          }
          case 34: {
            Policy = input.ReadBytes();
            break;
          }
          case 48: {
            transport_ = (global::Yoti.Auth.ProtoBuf.Qr.Transport) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
