// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataEntry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yoti.Auth.ProtoBuf.Share {

  /// <summary>Holder for reflection information generated from DataEntry.proto</summary>
  public static partial class DataEntryReflection {

    #region Descriptor
    /// <summary>File descriptor for DataEntry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataEntryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9EYXRhRW50cnkucHJvdG8SDnNoYXJlcHViYXBpX3YxIt0BCglEYXRhRW50",
            "cnkSLAoEdHlwZRgBIAEoDjIeLnNoYXJlcHViYXBpX3YxLkRhdGFFbnRyeS5U",
            "eXBlEg0KBXZhbHVlGAIgASgMIpIBCgRUeXBlEg0KCVVOREVGSU5FRBAAEgsK",
            "B0lOVk9JQ0UQARIXChNQQVlNRU5UX1RSQU5TQUNUSU9OEAISDAoITE9DQVRJ",
            "T04QAxIPCgtUUkFOU0FDVElPThAEEhsKF0FHRV9WRVJJRklDQVRJT05fU0VD",
            "UkVUEAUSGQoVVEhJUkRfUEFSVFlfQVRUUklCVVRFEAZCrwEKJGNvbS55b3Rp",
            "LmFwaS5jbGllbnQuc3BpLnJlbW90ZS5wcm90b0IORGF0YUVudHJ5UHJvdG9a",
            "DnlvdGlwcm90b3NoYXJlqgIYWW90aS5BdXRoLlByb3RvQnVmLlNoYXJlygIQ",
            "WW90aVxTaGFyZXB1YmFwaeICHFlvdGlcU2hhcmVwdWJhcGlcR1BCTWV0YWRh",
            "dGHqAhlZb3RpLlByb3RvYnVmLlNoYXJlcHViYXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Yoti.Auth.ProtoBuf.Share.DataEntry), global::Yoti.Auth.ProtoBuf.Share.DataEntry.Parser, new[]{ "Type", "Value" }, null, new[]{ typeof(global::Yoti.Auth.ProtoBuf.Share.DataEntry.Types.Type) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataEntry : pb::IMessage<DataEntry> {
    private static readonly pb::MessageParser<DataEntry> _parser = new pb::MessageParser<DataEntry>(() => new DataEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yoti.Auth.ProtoBuf.Share.DataEntryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataEntry(DataEntry other) : this() {
      type_ = other.type_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataEntry Clone() {
      return new DataEntry(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Yoti.Auth.ProtoBuf.Share.DataEntry.Types.Type type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yoti.Auth.ProtoBuf.Share.DataEntry.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private pb::ByteString value_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataEntry other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            type_ = (global::Yoti.Auth.ProtoBuf.Share.DataEntry.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the DataEntry message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("UNDEFINED")] Undefined = 0,
        [pbr::OriginalName("INVOICE")] Invoice = 1,
        [pbr::OriginalName("PAYMENT_TRANSACTION")] PaymentTransaction = 2,
        [pbr::OriginalName("LOCATION")] Location = 3,
        [pbr::OriginalName("TRANSACTION")] Transaction = 4,
        [pbr::OriginalName("AGE_VERIFICATION_SECRET")] AgeVerificationSecret = 5,
        [pbr::OriginalName("THIRD_PARTY_ATTRIBUTE")] ThirdPartyAttribute = 6,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
