// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThirdPartyAttribute.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yoti.Auth.ProtoBuf.Share {

  /// <summary>Holder for reflection information generated from ThirdPartyAttribute.proto</summary>
  public static partial class ThirdPartyAttributeReflection {

    #region Descriptor
    /// <summary>File descriptor for ThirdPartyAttribute.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ThirdPartyAttributeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlUaGlyZFBhcnR5QXR0cmlidXRlLnByb3RvEg5zaGFyZXB1YmFwaV92MRoX",
            "SXNzdWluZ0F0dHJpYnV0ZXMucHJvdG8ibAoTVGhpcmRQYXJ0eUF0dHJpYnV0",
            "ZRIWCg5pc3N1YW5jZV90b2tlbhgBIAEoDBI9ChJpc3N1aW5nX2F0dHJpYnV0",
            "ZXMYAiABKAsyIS5zaGFyZXB1YmFwaV92MS5Jc3N1aW5nQXR0cmlidXRlc0K5",
            "AQokY29tLnlvdGkuYXBpLmNsaWVudC5zcGkucmVtb3RlLnByb3RvQhhUaGly",
            "ZFBhcnR5QXR0cmlidXRlUHJvdG9aDnlvdGlwcm90b3NoYXJlqgIYWW90aS5B",
            "dXRoLlByb3RvQnVmLlNoYXJlygIQWW90aVxTaGFyZXB1YmFwaeICHFlvdGlc",
            "U2hhcmVwdWJhcGlcR1BCTWV0YWRhdGHqAhlZb3RpLlByb3RvYnVmLlNoYXJl",
            "cHViYXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Yoti.Auth.ProtoBuf.Share.IssuingAttributesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Yoti.Auth.ProtoBuf.Share.ThirdPartyAttribute), global::Yoti.Auth.ProtoBuf.Share.ThirdPartyAttribute.Parser, new[]{ "IssuanceToken", "IssuingAttributes" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ThirdPartyAttribute : pb::IMessage<ThirdPartyAttribute> {
    private static readonly pb::MessageParser<ThirdPartyAttribute> _parser = new pb::MessageParser<ThirdPartyAttribute>(() => new ThirdPartyAttribute());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ThirdPartyAttribute> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yoti.Auth.ProtoBuf.Share.ThirdPartyAttributeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ThirdPartyAttribute() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ThirdPartyAttribute(ThirdPartyAttribute other) : this() {
      issuanceToken_ = other.issuanceToken_;
      issuingAttributes_ = other.issuingAttributes_ != null ? other.issuingAttributes_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ThirdPartyAttribute Clone() {
      return new ThirdPartyAttribute(this);
    }

    /// <summary>Field number for the "issuance_token" field.</summary>
    public const int IssuanceTokenFieldNumber = 1;
    private pb::ByteString issuanceToken_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString IssuanceToken {
      get { return issuanceToken_; }
      set {
        issuanceToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "issuing_attributes" field.</summary>
    public const int IssuingAttributesFieldNumber = 2;
    private global::Yoti.Auth.ProtoBuf.Share.IssuingAttributes issuingAttributes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yoti.Auth.ProtoBuf.Share.IssuingAttributes IssuingAttributes {
      get { return issuingAttributes_; }
      set {
        issuingAttributes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ThirdPartyAttribute);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ThirdPartyAttribute other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IssuanceToken != other.IssuanceToken) return false;
      if (!object.Equals(IssuingAttributes, other.IssuingAttributes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IssuanceToken.Length != 0) hash ^= IssuanceToken.GetHashCode();
      if (issuingAttributes_ != null) hash ^= IssuingAttributes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IssuanceToken.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(IssuanceToken);
      }
      if (issuingAttributes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(IssuingAttributes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IssuanceToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(IssuanceToken);
      }
      if (issuingAttributes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IssuingAttributes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ThirdPartyAttribute other) {
      if (other == null) {
        return;
      }
      if (other.IssuanceToken.Length != 0) {
        IssuanceToken = other.IssuanceToken;
      }
      if (other.issuingAttributes_ != null) {
        if (issuingAttributes_ == null) {
          issuingAttributes_ = new global::Yoti.Auth.ProtoBuf.Share.IssuingAttributes();
        }
        IssuingAttributes.MergeFrom(other.IssuingAttributes);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IssuanceToken = input.ReadBytes();
            break;
          }
          case 18: {
            if (issuingAttributes_ == null) {
              issuingAttributes_ = new global::Yoti.Auth.ProtoBuf.Share.IssuingAttributes();
            }
            input.ReadMessage(issuingAttributes_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
